### ISSUE TITLE
Move legend and navigation tool

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/WEBTSA#100]
Right now the navigation tool is showing up in the bottom right corner and the legend for the map is showing up above that tool.  This makes the legend cover a large area of the toward the center of the map (not ideal). The legend should be moved to very bottom right corner and the navigation tool should be top left just under the tool to switch between map and satellite views.

**Comment by jcaraballo17** [comment]
Moved the zoom and street view controls to the top left.
