### ISSUE TITLE
Y-Axis Scaling Issue 

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/WEBTSA#101]
We have an issue with multiple series being plotted with the same units, and so share the same y-axis. In some cases, these series appear to be scaled differently. Examples:
1. Variable: Discharge_cms Sites: RB_CG_BA and RB_FD_AA.
   Here the series appear to be are scaled correctly.  In this case, RB_FD_AA was selected for plotting first and then RB_CG_BA added. 
   ![image](https://cloud.githubusercontent.com/assets/5023186/14176113/9a47376a-f70c-11e5-8f21-6b1dc83e77c4.png)
   Here are the same series plotted, but there is different scaling occurring between the two series. In this case, RB_CG_BA was selected for plotting first and then RB_FD_AA added.
   ![image](https://cloud.githubusercontent.com/assets/5023186/14176107/89268850-f70c-11e5-8303-cec857999d44.png)
2. Variable: WaterTemp_EXO, Sites: LR_WaterLab_AA and LR_Mendon_AA
   Here the variables appear to be scaled correctly. LR_Mendon_AA was selected for plotting first and then LR_WaterLab_AA added.
   ![image](https://cloud.githubusercontent.com/assets/5023186/14176620/24de349e-f70f-11e5-813d-de05b1eacc30.png)
   Here are the same series plotted, but there is different scaling occurring between then two series. In this case, LR_WaterLab_AA was selected first and then LR_Mendon_AA added. 
   ![image](https://cloud.githubusercontent.com/assets/5023186/14176671/6692370a-f70f-11e5-8ba5-24e77af9c3a5.png)

**Comment by Maurier** [comment]
A fix for this issue has been deployed.
http://data.iutahepscor.org/tsa/
