### ISSUE TITLE
Missing Data from Source/Watershed

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/WEBTSA#107]
Currently, the only iUTAH watershed/source for which there are data on the TSA is the Logan River. Red Butte Creek and the Provo River are missing. Entries for these watersheds are present in the catalog. Does this have anything to do with the influxdb deployment? @fryarludwig @Maurier

**Comment by fryarludwig** [comment]
this is most likely an influx issue. I'll look into it

**Comment by fryarludwig** [comment]
It looks like the issue we had with the H2O Utility, where it would fail intermittently if the iUTAH database server was under heavy load. RedButte and Provo occasionally just fail to respond and the webtsa-utilities script would continue updating everything else. On December 20th, for example, both RedButte and Provo were in the WebTSA, but most days one or both of them are not.

I've set the script to start at 7:30pm to try and avoid peak times, and created an issue to implement retries in the event a database returns no records. (https://github.com/UCHIC/webtsa-utilities/issues/3) What's the priority for that?

**Comment by AmberSJones** [comment]
I think this is fairly high priority - that's a problem if 2/3 of our watersheds are regularly not making it into our interface! The job to update the SeriesCatalog runs at 8:00 pm and 12:00 am, and hasn't been taking longer than 45 minutes. I am wondering if the 7:30 pm script and the 8:00 pm updates are interfering with each other? I thought this is what we agreed on - should I reschedule? Does the script only run at 7:30 pm or does it occur in the morning, too?

**Comment by horsburgh** [comment]
I agree with @AmberSJones - this needs to be high priority.

**Comment by fryarludwig** [comment]
I don't have enough time to write and fully test the hotfix today, so changing the run time is the safer way to make sure iUTAH's WebTSA includes all the data sets. I just ran the updater successfully from the server, so I set the run-time to 5:30pm because that's a known good time (at least on Fridays and weekends). It only runs once a day in the evenings. 

I'll check the updater periodically over the break and run it manually if needed to be sure the data series stay available. I'll finish the fix and testing right after the holiday.

**Comment by AmberSJones** [comment]
I can change the time in which the SeriesCatalog runs. If you run the script at 7:30 pm, how long does it take?

**Comment by fryarludwig** [comment]
At the current run time of 5:30, it's had two successful runs. Thanks part that updates the data series catalog takes about a minute, which is the part that was failing in the past, and the process that adds any new values to the influx database takes about two hours. The two-hour portion is not intensive at all, and doesn't affect which data series are visible to the WebTSA.

**Comment by fryarludwig** [comment]
We've had no failures since changing the run time to 5:30pm. I've also added the retry capability and this newer version is running on both the iUTAH and EnviroDIY application servers. I'll watch the logs over the next week and close the issue if there are no issues.
