### ISSUE TITLE
Handling -9999 Values

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/WEBTSA#109]
Have we discussed how to handle -9999 values in the TSA plotting? I'm of the opinion that we should ignore these values for plotting as displaying them washes out all other data. Since users cannot zoom in the y-axis direction, there is no way to view the actual data. Thoughts? @Maurier @horsburgh 

![image](https://user-images.githubusercontent.com/5023186/34300986-db547840-e6e7-11e7-97ee-336ec4ea93dd.png)

**Comment by horsburgh** [comment]
Yes - no data values should be filtered out prior to plotting.

**Comment by AmberSJones** [comment]
@Maurier will you address this?

**Comment by Maurier** [comment]
Yes, could you point me to a dataset containing these values?

**Comment by Maurier** [comment]
Nevermind. I got it from the screenshot. I'll look into it.

**Comment by Maurier** [comment]
@AmberSJones, @horsburgh logic to filter out no data values has been in place. However, these datasets do not have this field populated? Should we assume a default of -9999 when this definition is absent in the dataset?

**Comment by horsburgh** [comment]
None of the datasets have changed. The TSA is still accessing the same data it was accessing before, it's just now accessing the data from Kenny's InfluxDB cache of the data. So, somewhere the NoData values have gotten lost in the new implementation.

@Maurier - where do you look for the NoData value? Should it be in the catalog?

@fryarludwig - Any ideas why the NoData values are missing?

**Comment by Maurier** [comment]
I discussed this with Juan. It seems it was removed recently, but we'll work on putting it back in the catalog.

**Comment by fryarludwig** [comment]
The NoData values were parsed from the WaterML when loading up the plot, and Influx doesn't carry this data. I've added the NoData values to the database and webtsa-utilities, now we just need to update the front end.

**Comment by AmberSJones** [comment]
Just checking in on this issue - are we waiting for @Maurier to make the connection with the front end?

**Comment by Maurier** [comment]
Yes, I should have a fix deployed today.

**Comment by fryarludwig** [comment]
Fixes are deployed to iUTAH and EnviroDIY production servers

**Comment by AmberSJones** [comment]
This is addressed. Thanks, all.
