### ISSUE TITLE
File name issue

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/WEBTSA#119]
When exporting from the console window, the file name has extra, superfluous spaces.

![image](https://user-images.githubusercontent.com/5023186/35738429-1c8b43be-07ec-11e8-80e9-45ae54316685.png)

**Comment by horsburgh** [comment]
@fryarludwig - can you also have a look at this one and at least diagnose, if not fix.

**Comment by fryarludwig** [comment]
I'll fix this - it's a postgres thing where "character" column types fill all 50 characters always, and "character varying" allows you to use less than the maximum number of characters.

**Comment by fryarludwig** [comment]
This is fixed in the production databases for iUTAH and EnviroDIY's TSA. Close when you've tested this.
