### ISSUE TITLE
QualityControlLevel in the legend and the table

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/WEBTSA#90]
Need to add quality control level to
1. The legend for series plotted on the visualization tab
2. As a column displayed by default on the datasets tab

**Comment by AmberSJones** [comment]
We never aligned this to the left.

**Comment by Maurier** [comment]
It's finally aligned to the left. Hello from the future.

**Comment by jcaraballo17** [comment]
2014 hahahaha

**Comment by AmberSJones** [comment]
Hey, closing three years later!
