### ISSUE TITLE
Disclaimer on time series download needs a minor edit

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/WEBTSA#94]
The current disclaimer in the download file reads:

WARNING: These data may be provisional and subject to revision. The data are released
on the condition that neither iUTAH may be held liable for any damages resulting from its use. The following metadata describe the data in this file:

It should read:

WARNING: These data may be provisional and subject to revision. The data are released 
on the condition that neither iUTAH nor any of its participants may be held liable for any 
damages resulting from thier use. The following metadata describe the data in this file:

**Comment by Maurier** [comment]
This text was updated in the past as specified above.
