### ISSUE TITLE
Duplicated data in downloaded csv files

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/WEBTSA#98]
When a data series is exported to a csv file, the data may be repeated within the file. I am only seeing it happening when the data are QualityControlLevelID = 1, particularly with Variable = stage, but I haven't checked every data series...

The data are not repeated in the database and not repeated in the web service request response.

**Comment by Maurier** [comment]
@AmberSJones let me know if you are still seeing this issue. If so please elaborate a bit more.

**Comment by AmberSJones** [comment]
I can't duplicate this. Closing the issue.
