### ISSUE TITLE
Date range should not be persistent between plots

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/WEBTSA#99]
After plotting and unplotting a dataseries, the date range is used for the next plot and it may not have data points.
![capture2](https://cloud.githubusercontent.com/assets/4700505/10320740/36a08aaa-6c32-11e5-91c7-303a6d58c84b.PNG)

**Comment by Maurier** [comment]
This was fixed in the past and the date ranges are no longer persistent.
